### ISSUE TITLE
exports is not defined error

### ISSUE THREAD

**Issue by protoEvangelion** [metal/gulp-metal#57] opened 2017-08-07 18:43 UTC
Trying to run a stand alone ***modal*** component from the Yeoman generator (tried soy and jsx versions).

Getting this error in dev tools: 

![image](https://user-images.githubusercontent.com/20076677/29040783-33369564-7b65-11e7-949b-a7c4d2209fe4.png)

Here is where it is failing in the `incremental-dom-cjs.js` file:

![image](https://user-images.githubusercontent.com/20076677/29040832-5cdd4d90-7b65-11e7-8b3f-c13422f5ba5c.png)

I'm on **linux** and have tried multiple versions of `gulp-metal` and get the same error.

**Comment by bryceosterhaus** [comment] 2017-08-07 23:58
What node and npm version are you running?

**Comment by protoEvangelion** [comment] 2017-08-08 00:51
I've tried everything between node v4 - 8 and the associated npm versions

**Comment by bryceosterhaus** [comment] 2017-08-08 15:39
Are you able to get any metal components to build with gulp metal? I saw you tried with the boilerplate and got a similar issue. You might try cloning https://github.com/metal/metal-select and see if you get the same issue.

**Comment by bryceosterhaus** [comment] 2017-08-08 15:54
I tried to reproduce on both the boilerplate and with the yeoman generator and wasn't able to reproduce. Could you provide some more specific steps?

I ran latest generator-metal with these options
```bash
? How do you want to name your class? Modal
? What do you want your class to extend from? Component
? Which template language do you want to use? JSX
? Which build format will this component use? globals
? Is this component supposed to run on node environment? (that is, should other modules be able to "require" and use it?) Yes
? Do you want to use the default karma configuration? (if so, the karma.conf.js file won't be generated, since the gulp tasks will ha
ndle the config) No
? What's the GitHub username? my-user
? How would you describe this project? My awesome Metal.js project
```

Node v8.2.1
npm v5.3.0

**Comment by protoEvangelion** [comment] 2017-08-08 16:57
Just cloned the **metal-select component** and ran the **yeoman generator** with same node version and exact same options and received the same two errors.

I ran `npm install` and `gulp build` in both projects.

I dragged and dropped the demo into Chrome and tried opening it by running `npm start` to view it through `localhost:4000`.  **_Should I be trying something else?_**

The only other difference between our environments that I can imagine is either our browsers or OS.

I am running **Chrome v60** and **Ubuntu v17** (_tried it on Ubuntu v16 and Mint v18 as well_).

**Comment by bryceosterhaus** [comment] 2017-08-08 17:39
Oh I see. I thought you were running into this error in the build process. I am able to reproduce now.

In the mean time since gulp-metal seems to have an issue, it might be your best shot to checkout building with webpack.

**Comment by protoEvangelion** [comment] 2017-08-14 21:58
It looks a bit more involved than anticipated so it makes sense to wait for the [bundler refactor](https://github.com/metal/gulp-metal/issues/12) to something like rollup or webpack to resolve the issue.

**Comment by jbalsas** [comment] 2017-09-02 18:35
Hey @protoEvangelion, we are updating the demos to a global webpack-based build. We hope to complete them all by the end of next week, but you can check what it involves in https://github.com/metal/metal-select/commit/1dba133b8f8d7a0e6b166037694fd3171aaed652.

We also updated the `generator-metal` a while ago. Did you try version `4.0.0`? It should also include the webpack build.

**Comment by protoEvangelion** [comment] 2017-09-08 21:51
@jbalsas Will the webpack file also compile jsx files?  I just downloaded the component I was looking for and it works now with the new webpack config! Great work :)

**Comment by jbalsas** [comment] 2017-09-09 12:46
Hey @protoEvangelion, sure, just take a look at the [jsx examples](https://github.com/metal/metal-examples/tree/master/boilerplates/boilerplate-jsx). All you need is the proper webpack loaders and babel presets 😉 

Closing here, thanks for reporting!! 👍

**Closed as completed by jbalsas** 2017-09-09 12:46 UTC
